# Clippy configuration for AI-C TUI
# This file configures clippy linting rules

# Avoid false positives for expected module complexity
cognitive-complexity-threshold = 50
type-complexity-threshold = 500

# Allow longer function names for descriptive Git operations
too-many-arguments-threshold = 8
too-many-lines-threshold = 120

# Performance lints
avoid-breaking-exported-api = false

# TUI-specific allowances
# Allow certain patterns common in TUI development