# Rust formatting configuration (stable channel compatible)
# This file configures rustfmt for consistent code formatting

# Edition
edition = "2021"

# Line width
max_width = 100

# Basic formatting
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Functions
fn_params_layout = "Tall"

# Misc stable options
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true